import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>unimemo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <div className="flex justify-between space-x-1">
          <div className="w-1/2">
            <div className="bg-white rounded-lg shadow-lg w-full h-36">
              <p>a</p>
            </div>
          </div>
          <div>
            <p>a</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
