import type { NextPage } from "next";
import Head from "next/head";
import TopCard from "../components/molecules/cards/TopCard";

const Home: NextPage = () => {
  return (
    <div className="text-gray-900">
      <Head>
        <title>unimemo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <div className="lg:flex justify-between space-x-1">
          <div className="lg:w-1/2 md:w-full xs:w-11/12">
            {/* カード */}
            <TopCard />
          </div>
          <div>
            <p>a</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
